name: Build

on:
  push:
    branches:
      - "valhalla_python"
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "*.sh"

jobs:
  build_manylinux:
    name: manylinux_2_24_x86_64
    runs-on: ubuntu-20.04

    env:
      POLICY: manylinux_2_24
      PLATFORM: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: .buildx-cache-manylinux_2_24_x86_64/*
          key: buildx-cache-manylinux_2_24_x86_64-${{ hashFiles('docker/**') }}
          restore-keys: buildx-cache-manylinux_2_24_x86_64-

      - name: Build
        run: ./build.sh

      - name: Deploy image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/gis-ops/manylinux:valhalla_py
