name: Build

on:
  workflow_dispatch:
    inputs:
      useCache:
        description: Use GHA cache
        type: boolean
        required: false
        default: true
  push:
    branches:
      - "py-osrm"
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: ${{ matrix.policy }}_${{ matrix.platform }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        policy: ["manylinux2014", "manylinux_2_28"]
        platform: ["x86_64"]

    env:
      POLICY: ${{ matrix.policy }}
      PLATFORM: ${{ matrix.platform }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup cache
        if: github.event_name != 'workflow_dispatch' || fromJSON(github.event.inputs.useCache)
        uses: actions/cache@v3
        with:
          path: .buildx-cache-${{ matrix.policy }}_${{ matrix.platform }}/*
          key: buildx-cache-${{ matrix.policy }}-${{ matrix.platform }}-${{ hashFiles('docker/**') }}
          restore-keys: buildx-cache-${{ matrix.policy }}-${{ matrix.platform }}-
      
      - name: Get branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build
        run: ./build.sh

      - name: Push image
        run: |
          docker tag quay.io/pypa/${{ matrix.policy }}_${{ matrix.platform }}:${{ github.sha }} ghcr.io/gis-ops/${{ matrix.policy }}_${{ matrix.platform }}_${{ env.BRANCH }}
          docker image rm quay.io/pypa/${{ matrix.policy }}_${{ matrix.platform }}:${{ github.sha }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/gis-ops/${{ matrix.policy }}_${{ matrix.platform }}_${{ env.BRANCH }}

  all_passed:
    needs: [build_manylinux]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All jobs passed"
