name: Build

on:
  push:
    branches:
      - "valhalla_python"
      - "osrm_python"
    paths-ignore:
      - '*.md'

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: manylinux_2_24_x86_64
    runs-on: ubuntu-20.04

    env:
      POLICY: manylinux_2_24
      PLATFORM: x86_64
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: .buildx-cache-manylinux_2_24_x86_64/
          key: buildx-cache-manylinux_2_24_x86_64-${{ hashFiles('docker/**') }}
          restore-keys: buildx-cache-manylinux_2_24_x86_64-

      - name: Get branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build image
        run: ./build.sh

      - name: Push image
        run: |
          docker tag quay.io/pypa/manylinux_2_24_x86_64:${{ github.sha }} ghcr.io/gis-ops/manylinux:${{ env.BRANCH }}
          docker image rm quay.io/pypa/manylinux_2_24_x86_64:${{ github.sha }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/gis-ops/manylinux:${{ env.BRANCH }}
